export const logs = [
  {
    id: 1,
    team_id: 114,
    name: "Lausanne",
    url: "https://files.eliteprospects.com/layout/logos/lausanne_hc-4.png",
    position: 1,
    stat: {
      GP: 10,
      W: 8,
      L: 2,
      T: null,
      OTW: 2,
      OTL: 0,
      PTS: 22,
      GF: 31,
      GA: 23,
      GD: 8,
    },
    timestamp: "1605694200000",
  },
  {
    id: 2,
    team_id: 266,
    name: "Thurgau",
    url: "https://files.eliteprospects.com/layout/logos/hc_thurgau-2.png",
    position: 1,
    stat: {
      GP: 14,
      W: 9,
      L: 5,
      T: null,
      OTW: 2,
      OTL: 2,
      PTS: 27,
      GF: 45,
      GA: 34,
      GD: 11,
    },
    timestamp: "1605694200000",
  },
  {
    id: 3,
    team_id: 112,
    name: "Kloten",
    url: "https://files.eliteprospects.com/layout/logos/kloten_flyers-2.png",
    position: 2,
    stat: {
      GP: 10,
      W: 7,
      L: 3,
      T: null,
      OTW: 1,
      OTL: 0,
      PTS: 20,
      GF: 43,
      GA: 23,
      GD: 20,
    },
    timestamp: "1605694200000",
  },
  {
    id: 4,
    team_id: 117,
    name: "Zug",
    url: "https://files.eliteprospects.com/layout/logos/evz.png",
    position: 2,
    stat: {
      GP: 10,
      W: 8,
      L: 2,
      T: null,
      OTW: 2,
      OTL: 0,
      PTS: 22,
      GF: 33,
      GA: 25,
      GD: 8,
    },
    timestamp: "1605694200000",
  },
  {
    id: 5,
    team_id: 265,
    name: "Sierre",
    url: "https://files.eliteprospects.com/layout/logos/hc_sierre-2.png",
    position: 3,
    stat: {
      GP: 10,
      W: 6,
      L: 4,
      T: null,
      OTW: 0,
      OTL: 1,
      PTS: 19,
      GF: 34,
      GA: 32,
      GD: 2,
    },
    timestamp: "1605694200000",
  },
  {
    id: 6,
    team_id: 111,
    name: "Gottéron",
    url:
      "https://files.eliteprospects.com/layout/logos/hc_fribourg-gotteron-4.png",
    position: 3,
    stat: {
      GP: 11,
      W: 7,
      L: 4,
      T: null,
      OTW: 1,
      OTL: 1,
      PTS: 21,
      GF: 32,
      GA: 34,
      GD: -2,
    },
    timestamp: "1605694200000",
  },
  {
    id: 7,
    team_id: 440,
    name: "Bietigheim Steelers",
    url: "https://files.eliteprospects.com/layout/logos/bietigheim.png",
    position: 3,
    stat: {
      GP: 5,
      W: 3,
      L: 2,
      T: null,
      OTW: 1,
      OTL: 1,
      PTS: 9,
      GF: 20,
      GA: 15,
      GD: 5,
    },
    timestamp: "1605694200000",
  },
  {
    id: 8,
    team_id: 261,
    name: "GC/Küsnacht",
    url: "https://files.eliteprospects.com/layout/logos/gck.png",
    position: 4,
    stat: {
      GP: 11,
      W: 5,
      L: 6,
      T: null,
      OTW: 1,
      OTL: 3,
      PTS: 17,
      GF: 26,
      GA: 28,
      GD: -2,
    },
    timestamp: "1605694200000",
  },
  {
    id: 9,
    team_id: 260,
    name: "Genève-Servette",
    url: "https://files.eliteprospects.com/layout/logos/geneve-servette_hc.png",
    position: 4,
    stat: {
      GP: 8,
      W: 6,
      L: 2,
      T: null,
      OTW: 1,
      OTL: 1,
      PTS: 18,
      GF: 35,
      GA: 17,
      GD: 18,
    },
    timestamp: "1605694200000",
  },
  {
    id: 10,
    team_id: 118,
    name: "ZSC",
    url: "https://files.eliteprospects.com/layout/logos/zsc.png",
    position: 5,
    stat: {
      GP: 11,
      W: 6,
      L: 5,
      T: null,
      OTW: 1,
      OTL: 1,
      PTS: 18,
      GF: 35,
      GA: 36,
      GD: -1,
    },
    timestamp: "1605694200000",
  },
  {
    id: 11,
    team_id: 257,
    name: "Ajoie",
    url: "https://files.eliteprospects.com/layout/logos/hc_ajoie-2.png",
    position: 5,
    stat: {
      GP: 6,
      W: 6,
      L: 0,
      T: null,
      OTW: 2,
      OTL: 0,
      PTS: 16,
      GF: 34,
      GA: 15,
      GD: 19,
    },
    timestamp: "1605694200000",
  },
];
